###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
		"username": "admin1",
		"password": "admin1"
}

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
		"username": "admin1",
		"email": "admin1@gmail.com",
		"password": "admin1",
		"repeatPassword": "admin1"
}

###
POST http://localhost:5000/api/hotels
Content-Type: application/json

{
		"name": "Hotel 1",
		"type": "hotel",
		"city": "hcm",
		"address": "Address 1",
		"distance": 100,
		"title": "Title 1",
		"description": "Description 1",
		"rating": 10,
		"cheapestPrice": 300,
		"featured": true
}

###
GET http://localhost:5000/api/hotels

###
GET http://localhost:5000/api/rooms

###
DELETE http://localhost:5000/api/rooms/631a150f317b9c1ad233830b/631d925c3856ee7d6eec0e1a

###
POST http://localhost:5000/api/rooms/631d925c3856ee7d6eec0e1a
Content-Type: application/json

{
	"title": "Room 1",
	"price": 100,
	"maxPeople": "2",
	"description": "Description 1",
	"roomNumbers": [
			{
				"number": "101",
				"unavailableDates": []
			},
				{
				"number": "102",
				"unavailableDates": []
			},
			{
				"number": "103",
				"unavailableDates": []
			}
		]
}

###
GET http://localhost:5000/api/hotels/rooms/631a14f1317b9c1ad2338300

###
GET http://localhost:5000/api/hotels/find/631a14f1317b9c1ad2338300

###
PUT http://localhost:5000/api/rooms/availability/631a14f1317b9c1ad2338301
Content-Type: application/json

{
	"dates": "3000-10-13"
}